project:
  type: website

website:
  title: "Good Enough Coding in Science"
  navbar: true
  favicon: images/gecs-mark.png
  page-footer: by Igors Dubanevics | 2025-2026 | MIT License

  sidebar:
    style: "floating"
    # search: true
    contents: 
      - text: "Home"
        href: index.qmd
      - text: "Getting ready"
        href: lessons/setting-up.qmd
      - section: "Sessions"
        contents:
          - text: "1. Git and GitHub collaboration"
            href: lessons/version-control.qmd
          - text: "2. Reproducible project"
            href: lessons/project-structure.qmd
          - text: "3. Code quality and testing"
            href: lessons/testing.qmd
          - text: "4. Automation and publication"
            href: lessons/automation.qmd
      - section: "Reference"
        contents:
          - text: "VS Code"
            href: lessons/vs-code.qmd
          - text: "Terminal"
            href: lessons/terminal.qmd

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true
    mermaid:
      theme: neutral
    callout-appearance: simple
