project:
  type: website

website:
  title: "Good Enough Coding in Science"
  navbar: true
  favicon: images/gecs-mark.png
  page-footer: by Igors Dubanevics | 2025-2026 | MIT License

  sidebar:
    style: "floating"
    # search: true
    contents: 
      - text: "Home"
        href: index.qmd
      - text: "Setting Up"
        href: sessions/setting-up.qmd
      - section: "Sessions"
        contents:
          - text: "Git and GitHub Collaboration"
            href: sessions/version-control.qmd
          - text: "Reproducible Projects"
            href: sessions/virtual-environments.qmd
          - text: "Code Quality and Testing"
            href: sessions/testing.qmd
          - text: "Automation and Publication"
            href: sessions/automation.qmd
      - section: "Reference"
        contents:
          - text: "VS Code"
            href: sessions/vs-code.qmd
          - text: "Terminal"
            href: sessions/terminal.qmd

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true
    mermaid:
      theme: neutral
    callout-appearance: simple
