project:
  type: website

website:
  title: "Good Enough Coding in Science"
  navbar: true
  favicon: images/gecs-mark.png
  page-footer: by Igors Dubanevics | 2025-2026 | MIT License

  sidebar:
    style: "floating"
    # search: true
    contents: 
      - text: "Home"
        href: index.qmd
      - text: "Setting Up"
        href: lessons/setting-up.qmd
      - text: "Terminal"
        href: lessons/terminal.qmd
      - text: "Version Control"
        href: lessons/version-control.qmd
      - text: "Project Structure"
        href: lessons/project-structure.qmd
      - text: "Virtual Environments"
        href: lessons/virtual-environments.qmd
      - text: "Testing"
        href: lessons/testing.qmd
      - text: "Automation"
        href: lessons/automation.qmd
      - text: "VS Code"
        href: lessons/vs-code.qmd
      # - text: "About"
      #   href: about.qmd
      # -  auto: 0?_*

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true
    mermaid:
      theme: neutral
    callout-appearance: simple
