Output images/gecs-terminal.gif

Set FontSize 46
Set Width 1200
Set Height 400
Set TypingSpeed 50ms

# Clear the shell setup without capturing it.
Hide
Type "PS1=''"
Enter
Type "clear"
Enter
Show
Sleep 500ms

Type "Reproducible"
Sleep 1s
Backspace 13
Sleep 500ms

Type "Structured"
Sleep 1s
Backspace 10
Sleep 500ms

Type "Automated"
Sleep 1s
Backspace 9
Sleep 500ms

Type "Good"
Ctrl+V
Ctrl+J
Type "Enough"
Ctrl+V
Ctrl+J
Type "Coding"
Ctrl+V
Ctrl+J
Type "in"
Ctrl+V
Ctrl+J
Type "Science"
Sleep 2s

Backspace 40
Sleep 1s
